### PR TITLE
Prevent MOST occurrences of mouse position reset when opening a new menu

### PR DESCRIPTION
**Pull request by FeaturedSpace**
Essentially this will overwrite other MENUS when opening a new Menu, allowing for a smoother experience. This will make menus made with this plugin more professional and less clunky.

What do you think @kangarko @JavaFactoryDev ?

### CODE REVIEW

**Comment by kangarko** [comment]
Have you tested a sample plugin that uses onMenuClose function? This function is called in the InventoryCloseEvent and I have a feeling that it would break with this update.

**Comment by FeaturedSpace** [comment]
I haven't done a test of that sort yet, however, you could, of course, add another line that would account for that, calling onMenuClose in the controller logic.

**Comment by kangarko** [comment]
Thanks, but for now let's stick to what works, wouldn't want to break the system for so many people. Or, if simulating InventoryCloseEvent would be 100% safe then we can consider it, but you'd have to do extensive testing.

**Comment by FeaturedSpace** [comment]
I will begin extensive testing, but I do believe that this would work consistently.

**Comment by kangarko** [comment]
@FeaturedSpace how did the testing go?

**Comment by FeaturedSpace** [comment]
I haven't been able to yet due to personal issues. I will get this done tonight, no worries!

**Comment by FeaturedSpace** [comment]
After fairly extensive testing it seems we should be good to go!

**Comment by FeaturedSpace** [comment]
@kangarko

**Comment by FeaturedSpace** [comment]
Oh I forgot to push the other commit simulating the onMenuClose

**Comment by FeaturedSpace** [comment]
@lackoSK You can find the second commit in https://github.com/FeaturedSpace/Foundation/commit/935a4a606c04a70bdcac80f29c55e16182c09c99

**Pull request merged**
