### PR TITLE
Improved Region

### PR DESCRIPTION
**Pull request by solo-development**
Made some simple changes that had unnecessary if statements in a method.

### CODE REVIEW

**Comment by md5sha256** [comment]
What are you doing? There was a setter annotation from Lombok, and made the variable final - the setter will then fail at runtime.

**Comment by solo-development** [comment]
> What are you doing? There was a setter annotation from Lombok, and you made the variable final - the setter will then fail at runtime.

It should be fixed as of now. I originally had no errors on runtime with above but with future research I had a setting that was ignoring telling me about it for this specific project for some odd reason.

**Comment by md5sha256** [comment]
What are you doing with this? `entity#getLocation` is redundant?
```java
for (final Entity entity : getWorld().getChunkAt(cx, cz).getEntities()) {
					if (entity.isValid()) {
						entity.getLocation();
						if (isWithin(entity.getLocation())) found.add(entity);
					}
				}
```

**Comment by kangarko** [comment]
Not needed.

**Comment by kangarko** [comment]
Also we do not use JetBrains annotations, I code using Eclipse and try to make the code platform independent.

**Pull request closed without merging**
