### PR TITLE
Add support for nested hex colour declarations

### PR DESCRIPTION
**Pull request by md5sha256**

### CODE REVIEW

**Comment by kangarko** [comment]
Sounds epic! Just two clarifications:

1 The code loads fine for Minecraft 1.15 and lower?
2 Any performance drawback? You can use LagCatcher.testPerformance to run the test 1000 times with and without this enhancement to see if any differences are there.

Thanks again!

**Comment by md5sha256** [comment]
I don't see why this would fail on lower versions, the only thing I've done is to implement this as a BaseComponent[] as opposed to a single base component representing a message. Will test and comment the results.

**Comment by md5sha256** [comment]
I can confirm this does not break on 1.15 (I did not display output, but hex doesn't work on 1.15 anyway).

Results on 1.15 are:
My PR: 285.9ms, (avg 0.28ms) Existing: 292.67ms (avg 0.29) over 1000 runs.

Code for testing:

```java
ThreadLocalRandom random = ThreadLocalRandom.current();
        Collection<String> collection = new HashSet<>(20);
        for (int index = 0; index < 100; ) {
            StringBuilder builder = new StringBuilder(" ");
            for (int i = 0; i < 5; i++) {
                int r = random.nextInt(0, 255), g = random.nextInt(0, 255), b = random.nextInt(0, 255);
                builder.append("{").append(String.format("#%02x%02x%02x", r, g, b)).append("}Hello");
            }
            index+=5;
            collection.add(builder.toString());
        }
        final CommandSender sender  = new NullRouteCS();
        Runnable r = () -> {
            for (String s : collection) {
                Remain.sendJson(sender, "{text:s}", SerializedMap.of("s", s));
            }
        };  
 LagCatcher.testPerformance(1000, old ? "Hex", r);
```

**Comment by kangarko** [comment]
Awesome thanks!

**Comment by md5sha256** [comment]
I'll do some more testing but it seems odd it broke.

**Comment by md5sha256** [comment]
Ah I think I see what the issue is, I'll make another PR once I finish testing.

**Pull request merged**
