### PR TITLE
Update dependencies & switching to mariadb jdbc driver

### PR DESCRIPTION
**Pull request by ElBananaa**

### CODE REVIEW

**Comment by kangarko** [comment]
Thanks, please confirm that you've tested this on Minecraft 1.7.10, 1.8.8, 1.12 and 1.18 and I'll merge this :)

**Comment by ElBananaa** [comment]
This has only been tested under mc 1.16, 1.18.2 and mc 1.12.2 (java 8)
I did not run tests with lower mc versions since hikaricp implementation only works for 1.16+ versions.

**Comment by kangarko** [comment]
Thanks, I've done some extensive testing:

**1. MariaDb**
- Using MariaDB 10.5
- Connector: jdbc:mysql://{host}/{database}?autoReconnect=true&useSSL=false
- Results: Work everywhere (1.8.8-1.18.2)

**2. MySQL**
- Using MySQL 8.0
- Connector: same as above
- Results: 1.8.8 is broken, 1.12 and above works properly.

These use the current code in Foundation (for Hikari, driver is com.mysql.jdbc.Driver), if no Hikari, we use com.mysql.cj.jdbc.Driver and fall back to com.mysql.jdbc.Driver.

It works as-is right now, our customers can just keep using MariaDB for legacy MC versions and use MySQL or MariaDB for new versions, is there a good reason for this change or did I forget something? It's been a while since we first discussed this, sorry if I missed something!

**Comment by ElBananaa** [comment]
So far, no one has been complaining about it, but properly implementing this right now will definitely avoid further issues involving databases, which is why I recommended doing it the way LuckPerms, LiteBans and many other plugins does.
This way we can ensure users always use the latest driver for both MySQL and MariaDB (which means better stability) and also make sure they use the right driver (because I'm pretty sure using the latest driver (MySQL connectorJ for MySQL dbs and MariaDB one for MariaDB dbs) is the best practice here ^^

**Comment by kangarko** [comment]
@ElBananaa so sorry for my miserable reply times lately, I think we can keep the system "as-is" for users on Minecraft 1.15 and older. For Minecraft 1.16 and newer, we could use the "libraries" option in our plugin.yml to load the new versions of the libraries so that they can use latest drivers automatically -- could you help me with that please? You already had made the changes I just need a confirmation that this will work seamlessly for MC <1.16 and the latest one as well!

**Comment by ElBananaa** [comment]
@kangarko Alright, this is what I came with: https://github.com/kangarko/Foundation/pull/141/commits/76b8de7c14b3311175b244b64790fcb4990341e6

This will allow users for versions above 1.16 to be able to chose between updated versions of mysql and mariadb jdbc drivers by either using `jdbc:mariadb://` or `jdbc:mysql://`

For users below 1.16, even tho we don't support hikaricp, we still check if the classes for updated drivers are available (in case the users find a way to provide their own drivers, or if another plugin does it) if so, we use these drivers, else, we use the legacy driver provided by spigot. Tried with both mariadb & mysql for mc 1.18.2, and it works perfectly fine in both cases.
I also tried with the legacy driver on mc 1.8.8, and once again, it works fine.

(Make sure to push https://github.com/kangarko/ChatControl-Red-Src/pull/18 for this to work properly).


This is clearly not the best nor the cleanest way to do this, but this seems to work fine with the tests I ran. I still believe the best thing to do here is to compile chatcontrol with HikariCP, mysql jdbc driver and mariadb jdbc driver (using the pom.xml file) so users can benefit from HikariCP and up-to-date jdbc drivers on versions below 1.16 too.

**Comment by kangarko** [comment]
Thank you so much!

**Comment by ElBananaa** [comment]
@kangarko Do you want me to start working on implementing HikariCP, and both MySQL & MariaDB drivers in chatcontrol directly (As I said in the latest paragraph above), so users below 1.16 could also use updated drivers and hikaricp?

**Comment by kangarko** [comment]
@ElBananaa surprise, I managed to work from bed and added a simple library loading mechanism so that we can now load ANY library for ANY minecraft version! (only tested 1.8.8 and still needs work):

https://github.com/kangarko/Foundation/commit/25127b935b2e203928c38fb70a0dea707607d279

I will let you know when this is finished. It will load automatically, here's the draft:

Plugin authors can override getLibraries() in their SimplePlugin. By default this gives a list of libraries from plugin.yml which is very basic but fast. They can override this to add their custom libraries with optional settings such as from-to Minecraft version where the library should be loaded.

**Comment by ElBananaa** [comment]
That looks sick! This is something that will definitely make a lot of players happy!

**Comment by kangarko** [comment]
Okay I had to scrap the proposed design, the new design simply uses "libraries" from plugin.yml for 1.16 and newer, for older  it uses "legacy-libraries".

I was able to get hikari loading and working on 1.8.8!

I still need to recover, mind taking some time off of my shoulder and test MySQL 8.0 and MariaDb (a new one preferably) on both 1.18 and 1.8.8 to see how my changes affected the loading?

**Comment by ElBananaa** [comment]
> Okay I had to scrap the proposed design, the new design simply uses "libraries" from plugin.yml for 1.16 and newer, for older it uses "legacy-libraries".
> 
> I was able to get hikari loading and working on 1.8.8!
> 
> I still need to recover, mind taking some time off of my shoulder and test MySQL 8.0 and MariaDb (a new one preferably) on both 1.18 and 1.8.8 to see how my changes affected the loading?

Sure, take your time! 
I'll run tests on my end and let you know down below.

**Comment by ElBananaa** [comment]
@kangarko Alright, so I did run tests with both mariadb and mysql under 1.18.2 & 1.8.8, and they both work fine!
However, I did encounter an issue: for users using any java version above java 8 and running a server below minecraft 1.16, HikariCP doesn't work, and i'm getting the following error: 
```
------------------------------------[ 01.04.2022 15:35:03 ]-----------------------------------
ChatControlRed 10.10.4 encountered a ReflectionException
Running CraftBukkit 1.8.8-R0.1-SNAPSHOT and Java 17.0.2
Plugins: LuckPerms v5.4.5, Vault v1.7.3-b131, ProtocolLib v4.8.0, ChatControlRed v10.10.4
----------------------------------------------------------------------------------------------

More Information: 
Unable to load library org.openjdk.nashorn:nashorn-core:15.3.
ReflectionException Error lookup up method addURL in class class java.net.URLClassLoader and her subclasses
	 at org.mineacademy.chatcontrol.lib.ReflectionUtil.getDeclaredMethod(ReflectionUtil.java:395)
	 at org.mineacademy.chatcontrol.lib.plugin.Library.load(Library.java:76)
	 at org.mineacademy.chatcontrol.lib.plugin.SimplePlugin.loadLibraries(SimplePlugin.java:395)
	 at org.mineacademy.chatcontrol.lib.plugin.SimplePlugin.onLoad(SimplePlugin.java:230)
	 at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugins(CraftServer.java:298)
	 at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:202)
InaccessibleObjectException Unable to make protected void java.net.URLClassLoader.addURL(java.net.URL) accessible: module java.base does not "opens java.net" to unnamed module @b688280
	 at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(Unknown Source)
	 at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(Unknown Source)
	 at java.base/java.lang.reflect.Method.checkCanSetAccessible(Unknown Source)
	 at java.base/java.lang.reflect.Method.setAccessible(Unknown Source)
	 at org.mineacademy.chatcontrol.lib.ReflectionUtil.getDeclaredMethod(ReflectionUtil.java:387)
	 at org.mineacademy.chatcontrol.lib.plugin.Library.load(Library.java:76)
	 at org.mineacademy.chatcontrol.lib.plugin.SimplePlugin.loadLibraries(SimplePlugin.java:395)
	 at org.mineacademy.chatcontrol.lib.plugin.SimplePlugin.onLoad(SimplePlugin.java:230)
	 at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugins(CraftServer.java:298)
----------------------------------------------------------------------------------------------
```

**Comment by kangarko** [comment]
Unsupported access on Java 15+ unfortunatelly. Closing as "wontfix". Users have to stick on Java 8 when they chose to use Minecraft 1.15 or older.

**Pull request merged**
