### PR TITLE
CORRECTLY merging pull request for simulating InventoryCloseEvent

### PR DESCRIPTION
**Pull request by FeaturedSpace**
This will prevent annoying mouse resets, while not losing the functionality of onMenuClose.

### CODE REVIEW

**Comment by kangarko** [comment]
CraftEventFactory is a NMS import, we do not support such ways of "working around" this problem

**Comment by md5sha256** [comment]
Would a solution which utilised Reflection be accepted?

**Comment by FeaturedSpace** [comment]
I was considering this. The fact remains, the GUIs in Foundation will be forever flawed if this is not implemented.

**Comment by md5sha256** [comment]
Looking at the fact that there are multiple reflection based "workarounds" in Foundation already present, I would think it would be an accepted solution. @kangarko has the final say though.

**Comment by kangarko** [comment]
I am fine with whatever works, my goal is to maintain the highest stability with hundreds of other plugins out there, and the fact that we have hundreds of students relying on this library.

@md5sha256 if you could do an extensive testing to confirm it works as expected using the latest Boss, ChatControl, CoreArena then sure, let's do it. If you need access to these resources, please PM kangarko on Spigot.

**Comment by md5sha256** [comment]
Righty, I'll draft up and impl and will contact you once I've gotten it ready. @FeaturedSpace if you'd like to take this on, feel free to do so.

**Pull request closed without merging**
