### PR TITLE
Improve ReflectionUtil

### PR DESCRIPTION
**Pull request by md5sha256**
Hi, this PR intends to add the ability to cache classes, methods, constructors and fields into ReflectionUtil. Hopefully this can improve performance for recursive method lookups. Currently:

- A new static inner class in ReflectionUtil - `ReflectionData<T>` has been added which hold 3 Maps, one for constructors, one for methods and one for fields.
- ReflectionData should be thread-safe (there are mutation guards), however, I have not added a guard for static classCache and reflectionDataCache in ReflectionUtil. Not really sure if one is warranted, however, it may make sense to add one (would like some feedback on this!)
- Changes to existing methods to used cached values where possible.
- Method overrides for reflective lookups with a param cache which indicates whether the looked-up value(s) should be cached.

This PR is untested. There are no breaking changes in the code (method invoker decides whether the constructor, field etc should be cached); However, I'm not entirely sure if there will be a noticeable improvement in performance.

### CODE REVIEW

**Comment by md5sha256** [comment]
Whilst I have still yet to test the code in this PR, I've marked this ready for review as I feel that most of the the "stupid" mistakes I have made when writing the code has been rectified. Feel free to give me suggestions as to what I can add / remove.

**Comment by kangarko** [comment]
Thank you, looks promising. I already asked you to PM me on Spigot in the other pull request, I will give you access to the premium plugins so you can test it but I am not going to pull this live on Spigot until:

1. Please measure objectively what the performance is
2. If there's a gain, I'll test it within all plugins internally and merge

**Comment by md5sha256** [comment]
Will do, thanks!

**Comment by md5sha256** [comment]
So I've done a very basic test (i'm not really sure how to design a test for this which is both dynamic and accurate but here is what I used: https://pastie.io/aftjgg.java

Results:

Average time for non-cached class lookup = ~ 0.25 ms [Total = ~ 49ms]
Average time for cached class lookup = ~ 0.2 ms [Total = ~ 40ms] (so around 10% improvement?)

For method lookups, there is a definite performance increase, here are the results (I haven't bothered to aggregate them since I feel this test isn't very accurate?) Results: https://pastie.io/jxrdmg.req

There definetly is a performance benefit if you are looking up classes. Methods too, but less so.

**Comment by md5sha256** [comment]
Also, I would like to mention I'd like to add a few more methods before the merge as I've now realised that (`#getDeclaredMethod`)  does not exist so I'll add those in.

**Comment by kangarko** [comment]
Thanks, love your analysis and glad to see the results!! So are we ready to merge? :)

**Comment by md5sha256** [comment]
I would say yes, but are there any more useful things I can implement before the merge (such as a full cache of all methods and fields perhaps?) I can forsee potential memory leaks if we cache a class which should be unloaded (i.e when a plugin is "unloaded" from the classpath).

**Comment by md5sha256** [comment]
I would also like to mention that it may be useful to add a utility unsafeCast method *somewhere*, I would think `Common` is a nice place for it. 

```java
@SuppresWarnings("unchecked")
public static <T> T unsafeCast(Object o) throws ClassCastException {
     return (T) o;
}
```

**Comment by kangarko** [comment]
Thanks, for the unsafeCast(Object o) please add this to ReflectionUtil instead.

**Comment by md5sha256** [comment]
Will push and then this will be ready to be merged!

**Pull request merged**
