### PR TITLE
Skull block bug fix for versions below 1.13

### PR DESCRIPTION
**Pull request by CoobMC**

### CODE REVIEW

**Comment by ElBananaa** [comment]
@CoobMC Could you please fix the conflicts and confirm that this has been tested and is ready to merge?

@kangarko I think you missed this PR ^^

**Comment by kangarko** [comment]
Thanks going to look at this manually

**Comment by CoobMC** [comment]
@kangarko

**Comment by kangarko** [comment]
Sorry, I pulled it right now, see https://github.com/kangarko/Foundation/commit/807a432acf737adfe7bd9a4447f33b72be9a8f3c and the commit above that.

**Pull request closed without merging**
