### PR TITLE
Fixed scoreboard issues

### PR DESCRIPTION
**Pull request by Tvhee-Dev**

### CODE REVIEW

**Review by kangarko — APPROVED** [review]

**Comment by kangarko** [comment]
Please check with duplicate entries.

**Comment by Tvhee-Dev** [comment]
I have found one problem: If I use
```
char colorChar = '§';
System.out.println(colorChar);
System.out.println(Character.toString(colorChar));
```

it works fine (standalone Java program). BUT if I print the same in the console
```
[19:27:34 INFO]: º
[19:27:34 INFO]: º0
```
I get these weird characters. This only happens to me if I use `ChatColor.COLOR_CHAR`
image

**Comment by Tvhee-Dev** [comment]
Ok so the problem has been solved by adding the color char as a String
`private static final String COLOR_CHAR = "\u00A7";`. I would recommend doing that because otherwise it gets converted to numbers. Duplicates are also no problem anymore now, because any team prefix / suffix could be the same
image

**Comment by Tvhee-Dev** [comment]
Yesterday I have tested it in full, this pull request is now ready to get merged!

**Comment by kangarko** [comment]
Love it, thanks Tijn!

**Comment by kangarko** [comment]
@Tvhee-Dev 

Doesn't work on 1.8.8 unfortunately:

This is my code in CoreArena:

a

Colors are not replaced automatically, please fix this:

a

If I replace them, I get kicked out from the game:

a

**Comment by kangarko** [comment]
@Tvhee-Dev please see my last two commits, I made it work, but I only estimated that the problem happens on MC 1.12, please test where it starts happening and if we can fix it in a better way :)

**Comment by Tvhee-Dev** [comment]
Ok, thanks for testing it out! I have seen the coloring issues and fixed them. I wasn't able to finish my work today, tomorrow I will have another look. I have found out that you can try putting 48 characters (minus colors = 44 characters) on the scoreboard, but I still have to test things. I will be currently testing in 1.8.8, if that is working, I am asking you to test in newer versions. I don't know the team prefix and suffix length in 1.13, but the team entry length is still 16 in that version

**Comment by kangarko** [comment]
@Tvhee-Dev please also test on 1.7.10, a few students use it for modding, but no need to spend too much time there, just cut the message in case it is oversized :) Thanks, waiting for your new pull request!

**Comment by Tvhee-Dev** [comment]
So today I have done some testing, and I have fixed all issues on 1.8.8! Please make sure to test it on all versions, I could not find time for it, unfortunately. I have also increased the line length (read commit message)

**Pull request merged**
