### PR TITLE
Add support for multiple decorations in ChatUtil#generateGradient

### PR DESCRIPTION
**Pull request by Ultimating**
This is a feature implemented in my premium plugin, UltraColorPro. I figured Foundation could benefit from this feature. I have tested it on my end and everything works.

-Ultimation

### CODE REVIEW

**Comment by kangarko** [comment]
Thank you and I would love to pull, but you are not following our contributor guidelines - the entire class is marked red and replaced. Reformat using the original formatting so the commit only renders the actual changes

**Comment by broken1arrow** [comment]
> Thank you and I would love to pull, but you are not following our contributor guidelines - the entire class is marked red and replaced. Reformat using the original formatting so the commit only renders the actual changes

This is a pain, that is why I turn of the save action. It always breaks the original formatting you need to be careful when you use ctrl + alt + l also and only mark the parts you want to format.

**Comment by Ultimating** [comment]
I thought I wasn't using save actions and disabled it before I committed and made this request. But there were some settings I didn't catch.

@kangarko The original reformatting should be restored in the 2 commits I pushed. Though, this is also the first pull request I've ever made, so not sure if I did what you asked correctly.

**Comment by kangarko** [comment]
Unfortunately the Files Changed still shows the whole thing changed, please open a new pull request with the fixed formatting instead

**Pull request closed without merging**
