### PR TITLE
Fix dye issues

### PR DESCRIPTION
**Pull request by lulu2002**
Just like the title says, reverse the altName and legacyName for all version can works fine.

### CODE REVIEW

**Comment by lulu2002** [comment]
oh , I just found the ROSE_RED should change to RED_DYE.

**Comment by FeaturedSpace** [comment]
Have you tested this version of Foundation on 1.8 - 1.15?

**Comment by kangarko** [comment]
Please confirm you have tested this on 1.8.8, 1.12.2, 1.13.2 and 1.14.4 versions.

**Comment by lulu2002** [comment]
Sorry about the reformatting, this is tested version.
Video link: https://youtu.be/SkopEFPtAt0

**Comment by kangarko** [comment]
Thanks for taking the time and making the video.

But how can I track the changes if the whole file is reformated? Can you please try sticking to the original format and just making the changes? It would really be beneficial.

**Comment by lulu2002** [comment]
Sure, let me do it right now.

**Comment by lulu2002** [comment]
Actually I just change some code in the "toMaterial()" method.

**Comment by kangarko** [comment]
Thanks lulu!

**Pull request merged**
