### PR TITLE
Add HeadUtil

### PR DESCRIPTION
**Pull request by md5sha256**
see #38 
Not really sure what to name the class, this code does compile; However it is untested.

### CODE REVIEW

**Comment by ItzRozzaDev** [comment]
This is used to get someone's skin hash, when i made the issue i forgot about **ItemCreator#ofSkullHash**  Having said that I am getting an error when trying to use it _"org.mineacademy.fo.ReflectionUtil$ReflectionException: Could not make instance of: class com.mojang.authlib.properties.Property"_

**Comment by ItzRozzaDev** [comment]
^^ could be due to foundation not having the dependency you added to the pom

**Comment by md5sha256** [comment]
> ^^ could be due to foundation not having the dependency you added to the pom

Makes no sense as AuthLib is present in Spigot?

**Comment by ItzRozzaDev** [comment]
here is full error

```
_[10:14:02 INFO]: [CustomEconomy] CustomEconomy 2.0.0 encountered a ReflectionException! Please check your error.log and report this issue with the information in that file.
[10:14:02 INFO]: org.mineacademy.fo.ReflectionUtil$ReflectionException: Could not make instance of: class com.mojang.authlib.properties.Property
[10:14:02 INFO]: at org.mineacademy.fo.ReflectionUtil.instantiate(ReflectionUtil.java:449)
[10:14:02 INFO]: at org.mineacademy.fo.menu.model.ItemCreator.ofSkullHash(ItemCreator.java:419)
[10:14:02 INFO]: at com.itzrozzadev.customeconomy.commands.TestCommand.onCommand(TestCommand.java:18)
[10:14:02 INFO]: at org.mineacademy.fo.command.SimpleCommand.execute(SimpleCommand.java:343)
[10:14:02 INFO]: at org.mineacademy.fo.command.SimpleCommandGroup$MainCommand.onCommand(SimpleCommandGroup.java:306)
[10:14:02 INFO]: at org.mineacademy.fo.command.SimpleCommand.execute(SimpleCommand.java:343)
[10:14:02 INFO]: at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159)
[10:14:02 INFO]: at java.lang.Thread.run(Thread.java:748)
[10:14:02 INFO]: java.lang.NoSuchMethodException: com.mojang.authlib.properties.Property.<init>(java.util.UUID, java.lang.String)
[10:14:02 INFO]: at java.lang.Class.getConstructor0(Class.java:3082)
[10:14:02 INFO]: at java.lang.Class.getDeclaredConstructor(Class.java:2178)
[10:14:02 INFO]: at org.mineacademy.fo.ReflectionUtil.instantiate(ReflectionUtil.java:443)
[10:14:02 INFO]: at org.mineacademy.fo.menu.model.ItemCreator.ofSkullHash(ItemCreator.java:419)
[10:14:02 INFO]: at com.itzrozzadev.customeconomy.commands.TestCommand.onCommand(TestCommand.java:18)
[10:14:02 INFO]: at org.mineacademy.fo.command.SimpleCommand.execute(SimpleCommand.java:343)
[10:14:02 INFO]: at org.mineacademy.fo.command.SimpleCommandGroup$MainCommand.onCommand(SimpleCommandGroup.java:306)
[10:14:02 INFO]: at org.mineacademy.fo.command.SimpleCommand.execute(SimpleCommand.java:343)
[10:14:02 INFO]: at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159)
[10:14:02 INFO]: at java.lang.Thread.run(Thread.java:748)
[10:14:02 INFO]: [CustomEconomy] !-----------------------------------------------------!
[10:14:02 INFO]: [CustomEconomy]  Failed to execute command /customecon test
[10:14:02 INFO]: [CustomEconomy] !-----------------------------------------------------!_
```

**Comment by ItzRozzaDev** [comment]
yes this is strange, can you test this out as well. Using ItemCreator#ofSkullHash my code
`final Player player = getPlayer();
		final ItemStack skull = ItemCreator.ofSkullHash("eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvZThlNmY3Nzk1ZGYyZWI4ZDdmNGZmNWQwYWVkNTI5YmU4MTEzNGQ5N2JiNTEyNjNlMzhjYjY5NGQ2NzA0ZGE0In19fQ==").build().make();
		PlayerUtil.addItems(player.getInventory(), skull);`

**Comment by md5sha256** [comment]
let me dig into the code of ItemCreator as there is now no reason to not directly import from AuthLib.

**Comment by ItzRozzaDev** [comment]
the code has worked for me in the past with no issue but now i am getting the above error, the code looks all good

**Comment by ItzRozzaDev** [comment]
the error happens here 

```
  Object gameProfile = ReflectionUtil.instantiate(ReflectionUtil.lookupClass("com.mojang.authlib.properties.Property"), new Object[]{UUID.randomUUID(), ""});
            Object property = ReflectionUtil.instantiate(ReflectionUtil.lookupClass("com.mojang.authlib.properties.Property"), new Object[]{"textures", hash});
            Object properties = ReflectionUtil.invoke("getProperties", gameProfile, new Object[0]);
```

**Comment by md5sha256** [comment]
O.o the constructor for AuthLib needs a String!

**Comment by md5sha256** [comment]
This should fix that issue, however, we made need to figure out a way to support older versions of AuthLib? I'll dig through the older versions on Spigot's Stash and see what versions we will need to support (if the diff isn't large I'll just use an if block + reflection for older versions).

**Comment by md5sha256** [comment]
I don't see AuthLib anywhere on the spigot servers, however, there should be an API for this in Paper (Its also present in Spigot but its not exposed).

**Comment by md5sha256** [comment]
I'm not really sure how best to proceed, we *could* have an explict dependency for AuthLib as its present at runtime (more importantly is not obfuscated). However, we could also just use reflection as we have been as of current. @kangarko, could you make the decision as to whether we should add AuthLib as a dependency or use reflection and APIs where possible? Adding AuthLib is sort of like depending on non-api code, which is much more stable (AuthLib was compiled in Java 5 - shows a lot).

**Comment by kangarko** [comment]
Sounds good, let me know what to place to pom.xml as a dependency for that authlib and I'll do it!

**Comment by md5sha256** [comment]
I can include the change in this PR, however, I'm more concerned about the fact that importing AuthLib is to a small extent likewise to importing NMS code. If you have no issues with it, I'll remake this PR as it quite messy.

**Comment by kangarko** [comment]
Can we just use the current system with reflection please?

**Comment by md5sha256** [comment]
I'll make a PR fixing the existing reflection and once tested will make another pr.

**Pull request closed without merging**
