### PR TITLE
Folia support (Not tested)

### PR DESCRIPTION
**Pull request by mani1232**
Also note that Folia does not support Scoreboard and Advancement apis### 

**It also needs to be tested**

### CODE REVIEW

**Comment by kangarko** [comment]
Please maintain your own fork, this will break things with Spigot/Paper/Bukkit. Also please test these changes, otherwise we can't pull them for safety reasons.

**Comment by mani1232** [comment]
> Please maintain your own fork, this will break things with Spigot/Paper/Bukkit. Also please test these changes, otherwise we can't pull them for safety reasons.

image

What should break in Spigot/Paper/Bukkit, I'm testing it at the moment

**Comment by kangarko** [comment]
We would still prefer you create a separate fork. Foundation is used by students in our programs and making these breaking changes will render their code invalid, I don't have the capacity to redo the entire program because of Folia.

**Comment by mani1232** [comment]
> We would still prefer you create a separate fork. Foundation is used by students in our programs and making these breaking changes will render their code invalid, I don't have the capacity to redo the entire program because of Folia.

You can create folia-support branch?

**Pull request closed without merging**
