### PR TITLE
Add reflection based workaround for PR #29

### PR DESCRIPTION
**Pull request by md5sha256**
Draft PR, I'd like to note there may be a potential issue which I've highlighted with a FIXME. This PR is a continuation of #29

### CODE REVIEW

**Comment by md5sha256** [comment]
Basically, `player#getOpenInventory` will *never* be null, we have to manually track when the server knows the player has opened an inventory and when they have closed it. 

Proposed: we add a tracker using either metadata (check if player has "open_inventory" attribute), or a runtime `Collection<UUID>`. Not sure which to implement but this is somewhat out of scope for this PR.

**Comment by kangarko** [comment]
Awesome thanks!

When the inventory is open, there is the metadata "Ka_Menu".

**Comment by md5sha256** [comment]
I haven't had the chance to test this yet and (as of this comment) the code was basically a copy paste (but using reflection) from #29. I'll run some tests after I give Issue #41 (as this is much more important) a go and #37 is merged

**Comment by md5sha256** [comment]
> Awesome thanks!
> 
> When the inventory is open, there is the metadata "Ka_Menu".

Does this apply for *all* inventories which a player has opened or just menus?

**Comment by md5sha256** [comment]
So, I think based off of what I've seen there may be a use-case for a util class which keeps track when a player has an inventory open. Essentially, it will just track `InventoryOpenEvent`, obviously this is out of scope for this PR but some thoughts/discussion on whether such a utility is worth adding to foundation would be nice.

**Comment by FeaturedSpace** [comment]
Thanks guys!

**Comment by md5sha256** [comment]
Couldn't find a way to get this to work on 1.16. Closing.

**Comment by kangarko** [comment]
I honestly think we are much better off with the current system. The cursor being reset is such a tiny annoyance compared to the complexity of this system and the 1000s of interconnections our students and users can experience breaking, let's forget about this.

**Pull request closed without merging**
