### PR TITLE
Update BlockUtil.java

### PR DESCRIPTION
**Pull request by EgehanKilicarslan**

### CODE REVIEW

**Comment by kangarko** [comment]
Can't this be simplified by calling the add(0.5, 0.5, 0.5) instead?

**Comment by EgehanKilicarslan** [comment]
I tried but it breaks the code

**Comment by broken1arrow** [comment]
> Can't this be simplified by calling the add(0.5, 0.5, 0.5) instead?

if you use add, it will only add on current location, for example if values is 158.877 and you add 0.5 it will then not be in center.

**Comment by kangarko** [comment]
Yeah agreed, the method is poorly named. I know what the op wants to achieve but I don't think we need this addition, use it on your own side for now.

**Pull request closed without merging**
