### PR TITLE
Scoreboard Improvements

### PR DESCRIPTION
**Pull request by Tvhee-Dev**
Hi, I have done some scoreboard improvements for Foundation.
1. I have cleaned up the code so it looks better
2. I have increased the line lengths for newer versions
3. I have done some general bugfixes

Using &c takes 2 characters. Since the text gets split in 3 parts, with colors = (total - (3 * 2)) = (total - 6)
 Maximum line lengths:
 - 1.8: 66 with colors, 70 without colors
 - 1.13: 98 with colors, 104 without colors
 - 1.18: 32889 with colors, 32895 without colors

 Maximum title lengths:
 - 1.8: 30 with colors, 32 without colors
 - 1.13: 126 with colors, 128 without colors

Note: Thanks for mentioning me in the Reflection video! Could you please also mention somewhere that I have contributed to the scoreboard (in the description or smth)? I would really appreciate it!

### CODE REVIEW

**Comment by kangarko** [comment]
Sorry for the delay.

Please use "tab" spacing instead of 4 spaces in IntelliJ because it will override the entire file difference so I cannot see what lines got changed -- it marks all lines in red, not just those that were changed.

**Comment by kangarko** [comment]
Thanks!

**Comment by kangarko** [comment]
Added credit here: https://app.mineacademy.org/lesson/1849 :)

**Comment by Tvhee-Dev** [comment]
Thanks for merging and adding the credits!

**Pull request merged**
